---
title: "Conformity of Norms Replication Visualizations"
author: "Group 5"
date: "August 24,2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = F, message = F, warning = F)
```

```{r libraries, include=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)


```

```{r}

df <- read_csv("01_raw_data.csv")

View(df)
```

```{r}

df_proc <- df %>% 
  select(
    -c(
      QUD,
      RT,
      optionLeft,
      optionRight,
      startDate,
      startTime,
      trial_number,
      question
  ))

View(df_proc)
```

```{r}

df_proc <- df_proc %>% 
  pivot_wider(names_from = "trial_name", values_from = "response")

View(df_proc)

```

```{r}

df_groups <- df_proc %>% 
  count(condition)

#View(df_groups)

ggplot(df_groups, aes(x = "", y = n, fill = factor(condition))) +
    geom_bar(stat = "identity", width = 1, col = "white") +
    #scale_fill_manual("condition",values=c("yellow", "blue", "red", "green")) +
    scale_fill_brewer("condition",palette = "Set1")+
    coord_polar("y", start=0) +
    theme_void()+
    ggtitle("Count")

        
```

```{r}
df_ratings <- df_proc %>% 
  group_by(condition, rate_statement) %>% 
  count()

#(df_ratings)

ggplot(df_ratings, aes(x = as.numeric(rate_statement), y = n, fill = factor(condition) ))+
  scale_fill_brewer("condition", palette = "Set1")+
  geom_bar(stat = "identity", width = 1, col = "white")+
  scale_x_discrete(name = "rating of statement", limits = c(seq(-5,5)))+
  ylab("count")
  

```

```{r}
df_md <- df_proc %>% 
  group_by(condition, experimental_trial) %>% 
  count()

#(df_ratings)

ggplot(df_md, aes(x = as.numeric(experimental_trial), y = n, fill = factor(condition) ))+
  scale_fill_brewer("condition", palette = "Set1")+
  geom_bar(stat = "identity", width = 1, col = "white")+
  scale_x_discrete(name = "rating of statement", limits = c(seq(1,6)))+
  ylab("count")
  

```

```{r}

ggplot(df_proc, aes(x = condition, y = as.numeric(experimental_trial) , fill = factor(condition) ))+
  scale_fill_brewer("condition", palette = "Set1")+
  geom_boxplot()+
  geom_jitter(width = 0.3, height = 0.1)
 # ylim(c("report",2,3,4,5, "leave alone"))
 # scale_y_discrete(name = "moral decision", limits = c(1,2,3,4,5,6))
  #ylab("count")
  

```
The higher the rating in the experimental trial the more the participant tends to leave the robber alone. In groups 2 and 4 the participant 

```{r}
#just for fun, no use intended

df_age <- df_proc %>% 
  drop_na()

df_age <- df_age[df_age$age < 100,]

df_age["Pro_Contra"] = case_when(
                        df_age$rate_statement > 0 ~ "Pro",
                        df_age$rate_statement < 0 ~ "Contra"
                        )


#View(df_age)
ggplot(df_age, aes(x = age, 
                   y = as.numeric(experimental_trial), 
                   col = choice_of_political_topic))+
  geom_point()+
  geom_smooth(method='lm', formula= y~x, col = "black")#+
  #scale_x_discrete("Age", limits= c(0,100))
```